services:
  cssg-admin-backend:
    image: cssg-admin-backend
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - 8787:8787
    environment:
      - PORT=8787
      - NEXT_PUBLIC_FRONTEND_URL=http://localhost:3003
  cssg-admin-frontend:
    image: cssg-admin-frontend
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    ports:
      - 3003:3000
    environment:
      - PORT=3000
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8787
